# Generated by Django 2.1.2 on 2018-12-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('length', models.IntegerField(default=0)),
                ('date_released', models.DateField(verbose_name='date of release')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('for_audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.Audiobook')),
            ],
        ),
    ]
